---
abstract: 'Prevent commits in a production environment.'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  Test::Exception: '0'
  Test::FailWarnings: '0'
  Test::Git: '0'
  Test::More: '0.94'
  Test::Type: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-GitHooks-Plugin-BlockProductionCommits
provides:
  App::GitHooks::Plugin::BlockProductionCommits:
    file: lib/App/GitHooks/Plugin/BlockProductionCommits.pm
    version: v0.1.0
requires:
  App::GitHooks: '0'
  Carp: '0'
  File::Slurp: '0'
  System::Command: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/guillaumeaubert/App-GitHooks-Plugin-BlockProductionCommits/issues
  homepage: https://metacpan.org/release/App-GitHooks-Plugin-BlockProductionCommits
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: https://github.com/guillaumeaubert/App-GitHooks-Plugin-BlockProductionCommits
version: v0.1.0
